package lib

// Pro Football Reference team keys
var PFR_TEAM_KEYS = map[string]string{
	"ARI": "crd",
	"ATL": "atl",
	"BAL": "rav",
	"BUF": "buf",
	"CAR": "car",
	"CHI": "chi",
	"CIN": "cin",
	"CLE": "cle",
	"DAL": "dal",
	"DEN": "den",
	"DET": "det",
	"GB":  "gnb",
	"HOU": "htx",
	"IND": "clt",
	"JAX": "jax",
	"KC":  "kan",
	"LAC": "sdg",
	"LAR": "ram",
	"LVR": "rai",
	"MIA": "mia",
	"MIN": "min",
	"NO":  "nor",
	"NE":  "nwe",
	"NYG": "nyg",
	"NYJ": "nyj",
	"PHI": "phi",
	"PIT": "pit",
	"SEA": "sea",
	"SF":  "sfo",
	"TB":  "tam",
	"TEN": "oti",
	"WSH": "was",
}
